/**
 * FINAL REPORT agent.
 *
 * Assembles the strongly-typed structured report from the per-symbol market
 * analysis, risk interpretation, and research thesis, plus an overall summary
 * and a clear disclaimer. Output is validated against the ReportSchema (Zod)
 * whether generated by the real LLM or the mock generator.
 *
 * The numeric market snapshot attached to each asset (`marketData`) is sourced
 * directly from the deterministic engine — never from LLM prose — so the UI
 * always renders exact deterministic figures regardless of provider.
 */

import { getLlmClient } from "@/lib/llm/client";
import { toReportMarketData } from "@/lib/analysis/report-data";
import type { AgentContext, ReportAgentResult } from "./types";

export async function runReportAgent(
  context: AgentContext
): Promise<ReportAgentResult> {
  const client = getLlmClient();

  const assets = Object.keys(context.analyses).map((symbol) => ({
    analysis: context.analyses[symbol],
    interpretation: context.interpretations[symbol],
    thesis: context.theses[symbol],
  }));

  const report = await client.generateReport(context.query, assets);

  // Enforce exact deterministic market numbers on every asset (authoritative
  // override, provider-independent).
  report.assets = report.assets.map((asset) => {
    const analysis = context.analyses[asset.symbol];
    return analysis ? { ...asset, marketData: toReportMarketData(analysis) } : asset;
  });

  context.report = report;
  return { report };
}
